//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_reservation.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserved_room
    {
        public int id { get; set; }
        public int number_of_rooms { get; set; }
        public int reservation_id { get; set; }
        public string status { get; set; }
    
        public virtual reservation reservation { get; set; }
    }
}
