//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_reservation.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotel_reservationEntities3 : DbContext
    {
        public hotel_reservationEntities3()
            : base("name=hotel_reservationEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<guest> guest { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<room_type> room_type { get; set; }
    }
}
