//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_reservation.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public System.DateTime date_in { get; set; }
        public System.DateTime date_out { get; set; }
        public string status { get; set; }
        public string made_by { get; set; }
        public Nullable<int> guest_id { get; set; }
    
        public virtual guest guest { get; set; }
    }
}
